# ENCODE API filtering parameters
cell_type: "K562"
assay_type: "ChIP-seq"
assembly: "GRCh38"
min_peaks: 3000

# Model parameters
window_size: 1100
inner_size: 1000
gc_tolerance: 0.03

# Dataset split
validation_chroms:
  - "chr21"

test_chroms:
  - "chr22"

# Output directories
beds_outdir: "data/beds"
fasta_outdir: "data/fasta"

# file coordinates
fasta: "hg38.fa"
fasta_url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz"
